# -----MODEL-----
d_mlp: 256
d_model: 64
mask_type: causal
n_blocks: 6
n_ctx: 32
n_heads: 8
name: jet
seed: 91

# -----TOKENIZER-----
vocab_size: 16384

# -----TRAINING-----
batch_size: 32
epochs: 1
grad_accumulation_steps: 1
dropout: 0.2

# -----DATASET-----
dataset: fineweb-edu
overlap: 4
n_workers: 2

# -----RESOURCES-----
cuda: True
autocast: True

# -----OPTIMIZER-----
optimizer:
  name: adamw
  params:
    weight_decay: 0.0001
    fused: True

# -----LR Schedule-----
lr_schedule:
  name: onecycle
  params:
    lr_max: 0.01
    pct_start: 0.1 # Percentage of training to increase lr for 

# -----VALIDATION----- 
log_per_val: 1000
temp: 1
val_prompt: Hello, my name is Jet. J.E.T. stands for

# -----LOGGING-----
wandb: True
eff_batch_per_log: 100

# -----PATH TEMPLATES-----
templates: configs/path_templates.yaml
